### ISSUE TITLE
Vagrant, Docker und Co.

### ISSUE THREAD

**Issue by shochdoerfer** [phpugmrn/talk-proposals#8]
### Name

tbd.

### Titel

tbd.

### Abstract

tbd.

**Comment by Jan0707** [comment]
Das ist ja ein doch ziemlich breites Themenfeld für einen Vortrag (~1h). Geht es dabei um eine richtige Einführung ? Oder einen Vergleich ? Oder ein Tutorial ?

**Comment by shochdoerfer** [comment]
Das ist eher als "Sammelidee" gedacht. Wenn du nur ein Thema abdecken kannst/willst, passt das auch. War nur generelles Feedback von den Teilnehmern zum grundsätzlichen "DevOps" Thema mal was hören zu wollen. Wir sind für alle Spielarten offen ;)
